name: Build On Linux
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: 下载安装文件
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m pip install pyinstaller
      - name: 打包
        run: |
          pyinstaller -F cDiskSaver.py
          curl -F "file=@dist/cDiskSaver" https://euserv1.0x11e.cf/aba/cdrivesaver/linux
